### ISSUE TITLE
Cannot link to internal page

### ISSUE THREAD

**Issue by thenewguy** [rfosterslo/wagtailplus#5]
It seems that the internal linking to pages doesn't work in rich text editor for me using wagtail 1.1.  I've tested using IE, Firefox, and Chrome.

I didn't notice at first because it does work for external and email links.  But the internal page chooser is broken.

Is this something I am doing or is wagtailplus.wagtaillinks not yet compatible with wagtail 1.1?

<img width="638" alt="1" src="https://cloud.githubusercontent.com/assets/77731/10237342/450e2744-687e-11e5-9006-e3eb8058415f.png">
<img width="638" alt="2" src="https://cloud.githubusercontent.com/assets/77731/10237345/49ea24b6-687e-11e5-92ed-6ab07bbbb107.png">
<img width="638" alt="3" src="https://cloud.githubusercontent.com/assets/77731/10237348/4c4753aa-687e-11e5-96a7-09a28ce08f7c.png">
<img width="638" alt="4" src="https://cloud.githubusercontent.com/assets/77731/10237350/4e97fa7e-687e-11e5-9abb-e129fbf463c9.png">

Just for comparison, the RichTextField page chooser works if wagtailplus.wagtaillinks is disabled:

<img width="638" alt="5" src="https://cloud.githubusercontent.com/assets/77731/10237419/3844aab4-687f-11e5-832c-cbab64b196da.png">
<img width="638" alt="6" src="https://cloud.githubusercontent.com/assets/77731/10237420/3a68eabc-687f-11e5-83b8-ab7173c47e6b.png">
<img width="638" alt="6 5" src="https://cloud.githubusercontent.com/assets/77731/10237451/93da9af0-687f-11e5-8fba-27a2a579a3b5.png">
<img width="638" alt="7" src="https://cloud.githubusercontent.com/assets/77731/10237421/3c88dd02-687f-11e5-8b21-884edddaa25e.png">

**Comment by thenewguy** [comment]
from pip freeze: 
wagtail==1.1
wagtailplus==0.3.4

**Comment by rfosterslo** [comment]
I'm unable to recreate this issue with wagtail 1.1 and wagtailplus 0.3.4 - both internal and external linking in the rich text editor appear to be working as intended:

![image](https://cloud.githubusercontent.com/assets/628672/10254619/ca9a3c92-68f9-11e5-8c82-685e2a4016a0.png)

Have you run `python manage.py collectstatic` since installing wagtailplus?  There's a JavaScript dependency ([STATIC]wagtaillinks/js/hallo-plugins/hallo-wagtaillink.js) that should be automatically included via `wagtailplus.wagtaillinks.wagtail_hooks.py`.

**Comment by rfosterslo** [comment]
Well, I spoke too soon.  Not sure what exactly is happening yet, but I'm seeing the same issue now.  I suspect it's something in the ModalWorkflow process.

**Comment by rfosterslo** [comment]
Fixed in master.

**Comment by thenewguy** [comment]
Installing from master fixes the issue for me.
